language: node_js
node_js:
  - "12"
  - "14"
  - "16"
before_install:
  - npm install -g codecov
install:
  - npm install
script:
  - npm test
  - npm run coverage
  - codecov
addons:
  code_climate:
    repo_token: ea0fa9b3d69bb5f8e2c75709f4dd8cf53c38baa892391304f134de07fdf82246
